DROP TABLE IF EXISTS $TRAFIC_PROPERTIES;

CREATE TABLE $TRAFIC_PROPERTIES (WGAEN_TYPE VARCHAR,
MAXSPEED INTEGER,
DAY_NB_VH INTEGER,
DAY_NB_HOURS INTEGER,
EV_NB_VH INTEGER,
EV_NB_HOURS INTEGER,
NIGHT_NB_VH INTEGER,
NIGHT_NB_HOURS INTEGER,
DAY_PERCENT_HV DOUBLE PRECISION,
EV_PERCENT_HV DOUBLE PRECISION,
NIGHT_PERCENT_HV DOUBLE PRECISION,
DAY_PERCENT_LV DOUBLE PRECISION,
EV_PERCENT_LV DOUBLE PRECISION,
NIGHT_PERCENT_LV DOUBLE PRECISION);

INSERT
	INTO
	$TRAFIC_PROPERTIES (WGAEN_TYPE,
	MAXSPEED,
	DAY_NB_VH,
	DAY_NB_HOURS,
	EV_NB_VH,
	EV_NB_HOURS,
	NIGHT_NB_VH,
	NIGHT_NB_HOURS,
	DAY_PERCENT_HV,
	EV_PERCENT_HV,
	NIGHT_PERCENT_HV,
	DAY_PERCENT_LV,
	EV_PERCENT_LV,
	NIGHT_PERCENT_LV)
VALUES ( 'Motorway',130,26103,12,7458,4,3729,8,0.25,0.35,0.45,0.75,0.65,0.55);

INSERT
	INTO
	$TRAFIC_PROPERTIES (WGAEN_TYPE,
	MAXSPEED,
	DAY_NB_VH,
	DAY_NB_HOURS,
	EV_NB_VH,
	EV_NB_HOURS,
	NIGHT_NB_VH,
	NIGHT_NB_HOURS,
	DAY_PERCENT_HV,
	EV_PERCENT_HV,
	NIGHT_PERCENT_HV,
	DAY_PERCENT_LV,
	EV_PERCENT_LV,
	NIGHT_PERCENT_LV)
VALUES ( 'Trunk road',110,17936,12,3826,4,2152,8,0.2,0.2,0.2,0.8,0.8,0.8);

INSERT
	INTO
	$TRAFIC_PROPERTIES (WGAEN_TYPE,
	MAXSPEED,
	DAY_NB_VH,
	DAY_NB_HOURS,
	EV_NB_VH,
	EV_NB_HOURS,
	NIGHT_NB_VH,
	NIGHT_NB_HOURS,
	DAY_PERCENT_HV,
	EV_PERCENT_HV,
	NIGHT_PERCENT_HV,
	DAY_PERCENT_LV,
	EV_PERCENT_LV,
	NIGHT_PERCENT_LV)
VALUES ( 'Major main road',80,7124,12,1069,4,712,8,0.2,0.15,0.1,0.8,0.85,0.9);

INSERT
	INTO
	$TRAFIC_PROPERTIES (WGAEN_TYPE,
	MAXSPEED,
	DAY_NB_VH,
	DAY_NB_HOURS,
	EV_NB_VH,
	EV_NB_HOURS,
	NIGHT_NB_VH,
	NIGHT_NB_HOURS,
	DAY_PERCENT_HV,
	EV_PERCENT_HV,
	NIGHT_PERCENT_HV,
	DAY_PERCENT_LV,
	EV_PERCENT_LV,
	NIGHT_PERCENT_LV)
VALUES ( 'Main road',80,7124,12,1069,4,712,8,0.2,0.15,0.1,0.8,0.85,0.9);

INSERT
	INTO
	$TRAFIC_PROPERTIES (WGAEN_TYPE,
	MAXSPEED,
	DAY_NB_VH,
	DAY_NB_HOURS,
	EV_NB_VH,
	EV_NB_HOURS,
	NIGHT_NB_VH,
	NIGHT_NB_HOURS,
	DAY_PERCENT_HV,
	EV_PERCENT_HV,
	NIGHT_PERCENT_HV,
	DAY_PERCENT_LV,
	EV_PERCENT_LV,
	NIGHT_PERCENT_LV)
VALUES ( 'Small main road',80,1400,12,400,4,200,8,0.15,0.1,0.05,0.85,0.9,0.95);

INSERT
	INTO
	$TRAFIC_PROPERTIES (WGAEN_TYPE,
	MAXSPEED,
	DAY_NB_VH,
	DAY_NB_HOURS,
	EV_NB_VH,
	EV_NB_HOURS,
	NIGHT_NB_VH,
	NIGHT_NB_HOURS,
	DAY_PERCENT_HV,
	EV_PERCENT_HV,
	NIGHT_PERCENT_HV,
	DAY_PERCENT_LV,
	EV_PERCENT_LV,
	NIGHT_PERCENT_LV)
VALUES ( 'Collecting road',50,700,12,200,4,100,8,0.1,0.06,0.03,0.9,0.94,0.97);

INSERT
	INTO
	$TRAFIC_PROPERTIES (WGAEN_TYPE,
	MAXSPEED,
	DAY_NB_VH,
	DAY_NB_HOURS,
	EV_NB_VH,
	EV_NB_HOURS,
	NIGHT_NB_VH,
	NIGHT_NB_HOURS,
	DAY_PERCENT_HV,
	EV_PERCENT_HV,
	NIGHT_PERCENT_HV,
	DAY_PERCENT_LV,
	EV_PERCENT_LV,
	NIGHT_PERCENT_LV)
VALUES ( 'Service road',30,350,12,100,4,50,8,0.05,0.02,0.01,0.95,0.98,0.99);

INSERT
	INTO
	$TRAFIC_PROPERTIES (WGAEN_TYPE,
	MAXSPEED,
	DAY_NB_VH,
	DAY_NB_HOURS,
	EV_NB_VH,
	EV_NB_HOURS,
	NIGHT_NB_VH,
	NIGHT_NB_HOURS,
	DAY_PERCENT_HV,
	EV_PERCENT_HV,
	NIGHT_PERCENT_HV,
	DAY_PERCENT_LV,
	EV_PERCENT_LV,
	NIGHT_PERCENT_LV)
VALUES ('Dead-end road',30,175,12,50,4,25,8,0.02,0.01,0,0.98,0.99,1);